// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Account struct {
	ID int64 `json:"id"`
	// positive
	Balance   string    `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

type Transaction struct {
	ID                   int64 `json:"id"`
	SourceAccountID      int64 `json:"source_account_id"`
	DestinationAccountID int64 `json:"destination_account_id"`
	// positive
	Amount    string    `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
