// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg *CreateAccountParams) (*Account, error)
	CreateTransaction(ctx context.Context, arg *CreateTransactionParams) (*Transaction, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteAllAccounts(ctx context.Context) error
	DeleteAllTransactions(ctx context.Context) error
	GetAccount(ctx context.Context, id int64) (*Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (*Account, error)
	UpdateAccount(ctx context.Context, arg *UpdateAccountParams) (*Account, error)
}

var _ Querier = (*Queries)(nil)
